version: '3.8'

services:
  merch-api:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:80
    environment:
      DatabaseConnectionOptions__ConnectionString: "Host=host.docker.internal;Port=54\
        28;Database=merch-api;Username=postgres;Password=merchApiPassword"
    depends_on:
      - merch-api-db

  supply-service:
    image: ghcr.io/ozon-edu-csharp-2021/supply-service:main
    environment:
      DbConfiguration__ConnectionString: "Host=host.docker.internal;Port=5426;Databas\
        e=supply-service;Username=postgres;Password=supplyServicePassword"
    hostname: supply-service
    depends_on:
      - supply-service-db

  emailing-service:
    image: ghcr.io/ozon-edu-csharp-2021/emailing-service:main
    hostname: emailing-service

  employees-service:
    image: ghcr.io/ozon-edu-csharp-2021/employees-service:main
    hostname: employees-service
    depends_on:
      - employees-service-db
    volumes:
      - ./src:/src

  stock-api:
    image: ghcr.io/ozon-edu-csharp-2021/stock-api:main
    hostname: stock-api
    environment:
      DatabaseConnectionOptions__ConnectionString: "Host=host.docker.internal;Port=54\
        27;Database=stock-api;Username=postgres;Password=stockApiPassword"
    depends_on:
      - stock-api-db

  employees-service-db:
    image: postgres:latest
    ports:
      - "5425:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: employees-service
    volumes:
      - ./db/employees-service-postgres-db/dbdata:/var/lib/postgresql/data"

  supply-service-db:
    image: postgres:latest
    ports:
      - "5426:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supplyServicePassword
      POSTGRES_DB: supply-service

  stock-api-db:
    image: postgres:latest
    ports:
      - "5427:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: stockApiPassword
      POSTGRES_DB: stock-api

  merch-api-db:
    image: postgres:latest
    ports:
      - "5428:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: merchApiPassword
      POSTGRES_DB: merch-api
    command: "-c log_statement=all"
