version: '3.8'

services:
  merch-api:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports: 
      - 5000:80
    environment:
      DatabaseConnectionOptions__ConnectionString: "Host=host.docker.internal;Port=5428;Database=merch-api;Username=postgres;Password=merchApiPassword"
    depends_on:
      - merch-api-db

  merch-api-db:
    image: postgres:latest
    ports:
      - "5428:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: merchApiPassword
      POSTGRES_DB: merch-api
    command: "-c log_statement=all"